### ISSUE TITLE
Something wrong for CIFAR experiments

### ISSUE THREAD

**Issue by ybpaopao** [samet-akcay/ganomaly#1]
HI! I run your code with pytorch0.3 + python3.5. I tried to run the demo in experiments/run_cifar.sh. But I met some index error. Error shows like follows:
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    main()
  File "train.py", line 44, in main
    model.train()
  File "/media/yangbiao/disk1/ganomaly-master/lib/model.py", line 307, in train
    self.train_epoch()
  File "/media/yangbiao/disk1/ganomaly-master/lib/model.py", line 272, in train_epoch
    for data in tqdm(self.dataloader['train'], leave=False, total=len(self.dataloader['train'])):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 719, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/cifar.py", line 83, in __getitem__
    img, target = self.train_data[index], self.train_labels[index]
IndexError: index 49369 is out of bounds for axis 0 with size 45000
Do you know why? I will appreciate your aid.

**Comment by samet-akcay** [comment]
I tried to replicate the error, but couldn't. By default the training data should be of size 45000, which is why the tensor size is 45000. Have you tried mnist? If so can you run python train.py --dataset cifar10?

**Comment by ybpaopao** [comment]
@samet-akcay Hi, I tried to run python train.py --dataset cifar10 as you mentioned. However, it raise the same problem as follows:
>> Training model Ganomaly.
  0%|                                                                                                                                                                               | 0/781 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 47, in <module>
    main()
  File "train.py", line 44, in main
    model.train()
  File "/media/yangbiao/disk1/ganomaly-master/lib/model.py", line 307, in train
    self.train_epoch()
  File "/media/yangbiao/disk1/ganomaly-master/lib/model.py", line 272, in train_epoch
    for data in tqdm(self.dataloader['train'], leave=False, total=len(self.dataloader['train'])):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 719, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/cifar.py", line 83, in __getitem__
    img, target = self.train_data[index], self.train_labels[index]
IndexError: index 48784 is out of bounds for axis 0 with size 45000
PS:  The index number (all numbers are larger than 45000) changes every time when I run "run python train.py --dataset cifar10". I guess whether the problem is caused by the version issue of the third-part libraries, such as torchvision and tqdm? 3Q

**Comment by samet-akcay** [comment]
Maybe. I've used torchvision 0.1.9 and tqdm 4.15.0. Do you get any error when you run mnist?

**Comment by caojinmeng** [comment]
@samet-akcay Yes, I got the same error when I run mnist. I will check the versions of torchvision and tqdm.

**Comment by ybpaopao** [comment]
@samet-akcay Yes, I got the same errors when I run mnist. I will check the versions of torchvision and tqdm.

**Comment by ybpaopao** [comment]
@samet-akcay Hi, I'm glad to tell you that I can enjoy your code when I use torchvision 0.1.9 and tqdm 4.15.0. So, I think you can update your readme file to avoid such errors. ３Ｑ!
