### ISSUE TITLE
Training on UCSD PED1

### ISSUE THREAD

**Issue by mimirobo** [samet-akcay/ganomaly#10]
I've trained this network on "UCSD PED1" with the following options:

```
> ------------ Options -------------
> alpha: 50
> anomaly_class: abnormal
> batchsize: 16
> beta1: 0.5
> dataroot: 
> dataset: PED1
> display: True
> display_id: 0
> display_port: 8097
> display_server: http://localhost
> droplast: True
> extralayers: 0
> gpu_ids: [0]
> isTrain: True
> isize: 128
> iter: 0
> load_weights: False
> lr: 0.0002
> manualseed: None
> model: ganomaly
> name: ganomaly/PED1
> nc: 3
> ndf: 64
> ngf: 64
> ngpu: 1
> niter: 1200
> nz: 512
> outf: ./output
> phase: train
> print_freq: 100
> resume: 
> save_image_freq: 100
> save_test_images: False
> workers: 8
> -------------- End ----------------
```

and the result I've got is as follow:

```
> Loss: [0/1200] err_d: 13.113 err_g: 31.230 err_d_real: 0.000 err_d_fake: 13.113 err_g_bce: 27.631 err_g_l1l: 0.069 err_g_enc: 0.168 
>    Avg Run Time (ms/batch): 6.692 EER: 0.450 AUC: 0.558 max AUC: 0.558
>    Loss: [1/1200] err_d: 2.959 err_g: 30.650 err_d_real: 0.119 err_d_fake: 2.840 err_g_bce: 27.631 err_g_l1l: 0.057 err_g_enc: 0.154 
>    Avg Run Time (ms/batch): 5.997 EER: 0.519 AUC: 0.453 max AUC: 0.558
>    Loss: [2/1200] err_d: 1.915 err_g: 27.692 err_d_real: 0.825 err_d_fake: 1.090 err_g_bce: 24.081 err_g_l1l: 0.070 err_g_enc: 0.122 
>    .
>    .
>    .
>    .
>    Loss: [1086/1200] err_d: 24.558 err_g: 0.692 err_d_real: 24.558 err_d_fake: 0.000 err_g_bce: 0.000 err_g_l1l: 0.014 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 6.892 EER: 0.404 AUC: 0.642 max AUC: 0.670
>    Loss: [1087/1200] err_d: 1.565 err_g: 0.826 err_d_real: 0.965 err_d_fake: 0.599 err_g_bce: 0.001 err_g_l1l: 0.016 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 7.184 EER: 0.401 AUC: 0.641 max AUC: 0.670
>    Loss: [1088/1200] err_d: 1.789 err_g: 0.788 err_d_real: 1.307 err_d_fake: 0.481 err_g_bce: 0.000 err_g_l1l: 0.016 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 7.295 EER: 0.401 AUC: 0.644 max AUC: 0.670
>    Loss: [1089/1200] err_d: 18.843 err_g: 0.708 err_d_real: 18.843 err_d_fake: 0.000 err_g_bce: 0.000 err_g_l1l: 0.014 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 7.100 EER: 0.406 AUC: 0.639 max AUC: 0.670
>    Loss: [1090/1200] err_d: 13.253 err_g: 28.329 err_d_real: 0.000 err_d_fake: 13.253 err_g_bce: 27.631 err_g_l1l: 0.014 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 6.469 EER: 0.406 AUC: 0.647 max AUC: 0.670
>    Loss: [1091/1200] err_d: 3.089 err_g: 28.403 err_d_real: 0.060 err_d_fake: 3.029 err_g_bce: 27.631 err_g_l1l: 0.015 err_g_enc: 0.001 
>    Avg Run Time (ms/batch): 7.284 EER: 0.402 AUC: 0.644 max AUC: 0.670
```

and i believe that there's something wrong with the configurations I've applied.
Have you already tried this network on UCSD? 
I was wondering if you'd mind letting me know what is missing in training options or any other facts I must consider.

**Comment by samet-akcay** [comment]
Hi,

No, I haven't trained the model on UCSD. From the first glance, I would say that the issue is probably the image size, which you set to 128. The input image size of UCSD, however, is sth around 200s (correct me if I'm wrong). The problem is probably due to resizing the input images down to 128, which means that you lose information, resulting in a decrease in the overall performance. Also, the performance of DCGAN decreases when we train 128x128 images. 

What you could do is to perform sth like sliding window patches over the UCSD dataset, and train Ganomaly on that. After that, you could evaluate the performance based on the sliding-window patches, which is something we have done for the UBA dataset in the paper.

**Comment by mimirobo** [comment]
Thanks for your reply @samet-akcay 
I tried to set the image size on 256 at first but I got this error:
```
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):                                              
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 28, in main
    model.train()
  File "........./lib/model.py", line 303, in train
    self.train_epoch()
  File "........./lib/model.py", line 273, in train_epoch
    self.optimize()
  File "........./lib/model.py", line 206, in optimize
    self.update_netg()
  File "........./lib/model.py", line 198, in update_netg
    self.optimizer_g.step()
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/adam.py", line 56, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
```
which is due to my gpu. That's why I'm trying on 128.
Thanks for your sliding window advice I'll give it a try.

**Comment by ybpaopao** [comment]
@mimirobo Hi, I also want to perform GANomaly in UCSD or other datasets used for anomaly detection. Does it perform well in video datasets? Could you please send me an email so we can discuss some details.
