### ISSUE TITLE
error: expected input[64, 1, 32, 32] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by zszzlmt** [samet-akcay/ganomaly#18]
hi, when I switched to Linux with Nvdia GPU, I met a new problem. when I use command like this:
```
python3 train.py --dataset mnist --niter 20 --anomaly_class 5
python3 train.py --dataset cifar10 --niter 20 --anomaly_class cat
```
I tried on mnist and cifar 10, the result is the same like this:
```
root@z-Precision-Tower-3620:/home/z/桌面/git/ganomaly#` python3 train.py --dataset mnist --niter 20 --anomaly_class 5
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
>> Training model Ganomaly.
Traceback (most recent call last):                                              
  File "train.py", line 43, in <module>
    model.train()
  File "/home/z/桌面/git/ganomaly/lib/model.py", line 279, in train
    self.train_epoch()
  File "/home/z/桌面/git/ganomaly/lib/model.py", line 249, in train_epoch
    self.optimize()
  File "/home/z/桌面/git/ganomaly/lib/model.py", line 181, in optimize
    self.update_netd()
  File "/home/z/桌面/git/ganomaly/lib/model.py", line 134, in update_netd
    self.out_d_real, self.feat_real = self.netd(self.input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/桌面/git/ganomaly/lib/networks.py", line 153, in forward
    features = self.features(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[64, 1, 32, 32] to have 3 channels, but got 1 channels instead
```
Can you help me to fix this? Thx!

**Comment by samet-akcay** [comment]
Hi, the problem is that when you use MNIST dataset, you need to specify the number of channels `--nc 1`. We use the MNIST dataset class that comes with PyTorch, which has only one channel. So, when you want to train MNIST, you should do the following:
```
python3 train.py --dataset mnist --nc 1 --niter 20 --anomaly_class 5
```

**Comment by zszzlmt** [comment]
> Hi, the problem is that when you use MNIST dataset, you need to specify the number of channels `--nc 1`. We use the MNIST dataset class that comes with PyTorch, which has only one channel. So, when you want to train MNIST, you should do the following:
> 
> ```
> python3 train.py --dataset mnist --nc 1 --niter 20 --anomaly_class 5
> ```

Thanks very much!!
