### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by yoheikikuta** [samet-akcay/ganomaly#26]
Thanks for an awesome repository.

I met the error of the issue title when executing `run_mnist.sh` in my GPU environment.

```
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    model.train()
  File "/work/lib/model.py", line 280, in train
    res = self.test()
  File "/work/lib/model.py", line 354, in test
    auc = evaluate(self.gt_labels, self.an_scores, metric=self.opt.metric)
  File "/work/lib/evaluate.py", line 24, in evaluate
    return roc(labels, scores)
  File "/work/lib/evaluate.py", line 43, in roc
    fpr, tpr, _ = roc_curve(labels, scores)
  File "/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 618, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 394, in _binary_clf_curve
    y_type = type_of_target(y_true)
  File "/root/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 249, in type_of_target
    if is_multilabel(y):
  File "/root/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 140, in is_multilabel
    y = np.asarray(y)
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 450, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

My GPU environments:
- nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
- Anaconda3-2018.12-Linux-x86_64
- PyTorch version: 1.0.0

The error was fixed by adding `.cpu()` method in https://github.com/yoheikikuta/ganomaly/blob/master/lib/evaluate.py#L22-L23 as below:

```
def evaluate(labels, scores, metric='roc'):
    labels = labels.cpu()
    scores = scores.cpu()
    if metric == 'roc':
...
```

Is this a known issue?
If not, I'll send a PR to fix it.

**Comment by yhxuyou** [comment]
hello,I have done this,but i got an another problem like this,and how can i to deal with it?
```
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    model.train()
  File "/data4/xyz/genarmal/lib/model.py", line 280, in train
    res = self.test()
  File "/data4/xyz/genarmal/lib/model.py", line 354, in test
    auc = evaluate(self.gt_labels, self.an_scores, metric=self.opt.metric)
  File "/data4/xyz/genarmal/lib/evaluate.py", line 30, in evaluate
    return roc(labels, scores)
  File "/data4/xyz/genarmal/lib/evaluate.py", line 55, in roc
    fpr, tpr, _ = roc_curve(labels, scores)
  File "/usr/local/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 534, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/usr/local/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 318, in _binary_clf_curve
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: multiclass format is not supported
```

**Comment by samet-akcay** [comment]
This issue shows up when you use PyTorch v1.0. For v0.5, and less, it works fine. I'll try to fix it when I've free time.

**Comment by samet-akcay** [comment]
@yoheikikuta, Thanks for your feedback, the repo has now been updated.

**Comment by samet-akcay** [comment]
@yhxuyou, I'm not sure, but your problem sounds more like that your data. It sounds like your data is a multi-class dataset, which would not work in this case since this repo only accepts binary class at the moment.

**Comment by yoheikikuta** [comment]
Since the original issue was solved, I'll close the issue.
Thanks.
