### ISSUE TITLE
train on cirf10

### ISSUE THREAD

**Issue by lzzlxxlsz** [samet-akcay/ganomaly#36]
when I run the train.py ,it turns a wrong error :
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data\cifar-10-python.tar.gz
100%|█████████▉| 170483712/170498071 [3:27:33<00:01, 10548.55it/s]Files already downloaded and verified
Traceback (most recent call last):
  File "D:/Anaconda/envs/tensorflow/ganomaly-master/train.py", line 35, in <module>
    dataloader = load_data(opt)
  File "D:\Anaconda\envs\tensorflow\ganomaly-master\lib\data.py", line 60, in load_data
    trn_img=dataset['train'].train_data,
AttributeError: 'CIFAR10' object has no attribute 'train_data'
Exception ignored in: <function tqdm.__del__ at 0x0000000005FE9620>
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\tqdm\_tqdm.py", line 931, in __del__
    self.close()
  File "D:\Anaconda\lib\site-packages\tqdm\_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "D:\Anaconda\lib\site-packages\tqdm\_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "D:\Anaconda\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "D:\Anaconda\lib\threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

my computer envrionmenr is windows cpu

**Comment by samet-akcay** [comment]
Hi, I'm closing this issue since the latest version handles this. Please reopen if you still encounter this issue with the latest version.
