### ISSUE TITLE
ValueError: multiclass format is not supported

### ISSUE THREAD

**Issue by DengMiao55** [samet-akcay/ganomaly#46]
Hi，I tried your new update code 。but I got this error  

Traceback (most recent call last):
  File "train.py", line 43, in <module>
    train()
  File "train.py", line 40, in train
    model.train()
  File "/home/dl/VSST/dm/ganomaly-master/lib/model.py", line 168, in train
    res = self.test()
  File "/home/dl/VSST/dm/ganomaly-master/lib/model.py", line 259, in test
    auc = evaluate(self.gt_labels, self.an_scores, metric=self.opt.metric)
  File "/home/dl/VSST/dm/ganomaly-master/lib/evaluate.py", line 24, in evaluate
    return roc(labels, scores)
  File "/home/dl/VSST/dm/ganomaly-master/lib/evaluate.py", line 46, in roc
    fpr, tpr, _ = roc_curve(labels, scores)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 622, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 396, in _binary_clf_curve
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: multiclass format is not supported

**Comment by samet-akcay** [comment]
Hi, can you tell me what was the command you run on the terminal to get the error?

**Comment by DengMiao55** [comment]
@samet-akcay     
python train.py --dataset cifar10 --abnormal_class ariplane 
when I print the net ,I also find the discriminator‘s structure is not same as the paper。 it lacks the fourth conv 。512。 does it matter？

**Comment by DengMiao55** [comment]
@samet-akcay ， I find the second question is in skipganomaly . And in skipganoamly,is the discriminator loss right?  I think it shouldn't have err_g_lat

**Comment by gewenchao** [comment]
> @ samet-akcay，我发现第二个问题是skipganomaly。在skippganoamly中，鉴别器损失正确吗？我认为它不应该有err_g_lat

hi,I met the same question in your topic description, can you tell me how you handle this problem?

**Comment by gwc2017180303** [comment]
> @ samet-akcay，我发现第二个问题是skipganomaly。在skippganoamly中，鉴别器损失正确吗？我认为它不应该有err_g_lat
Hi,I met the same question in your topic description, can you tell me how you handle this problem about 'multiclass format is not supported'.

**Comment by Ttt749** [comment]
Hi, I also meet the same question, Have you fixed it? Can you help me?
